/*
 * This Java source file was generated by the Gradle 'init' task.
 */
 

package JoshA;


import org.springframework.boot.SpringApplication; 
import org.springframework.boot.autoconfigure.SpringBootApplication; 
import org.springframework.boot.builder.SpringApplicationBuilder; 
import org.springframework.boot.web.servlet.support.SpringBootServletInitializer;


@SpringBootApplication 
public class Main extends SpringBootServletInitializer{
    //To configure app when deployed to an application server 
    
    public static void main(String[] args){
        
        SpringApplication.run(Main.class, args); 
    }
    
    @Override  protected SpringApplicationBuilder configure(SpringApplicationBuilder application){
        
        return application.sources(Main.class);
    }
}
